{
  parserClass="org.intellij.knd.parser.KndParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Knd"
  psiImplClassSuffix="Impl"
  psiPackage="org.intellij.knd.psi"
  psiImplPackage="org.intellij.knd.psi.impl"

  elementTypeHolderClass="org.intellij.knd.psi.KndTypes"
  elementTypeClass="org.intellij.knd.psi.KndElementType"
  tokenTypeClass="org.intellij.knd.psi.KndTokenType"
}

ROOT ::= DEF_BEGIN (DELIM C_END?)?

DEF_BEGIN ::= def_item_*

private def_item_ ::= DEF_DEFINITION | DEF_COMMENT

DEF_DEFINITION ::= DEF_KEY DEF_SEPARATOR DEF_VALUE

DEF_KEY ::= (DEF_KEY_KNOWN | DEF_KEY_UNKNOWN) (DEF_DOT DEF_PLATFORM)?

C_END ::= DIGIT*


